language: node_js
node_js:
  - "0.10"

rvm:
  - "1.8.7"  

install:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower
  - npm install
  - bower install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm test